export const PORTAL_HOME_URL = "https://portal.cpevalencia.com/";
// Only these standalone Noray iframe routes were verified without a Portal CPE session.
// Credential-bearing destinations are generated by the server on demand.
export const PORTAL_LINK_GROUPS = [
  {
    title: "Consultas",
    links: [
      { label: "¿Dónde voy? · Orden de servicio", section: "donde-voy" },
      { label: "Jornales y primas", section: "jornales" },
      { label: "Mis especialidades", section: "mis-especialidades" },
      { label: "Disponibilidad · últimos 12 meses", section: "disponibilidad12m" },
      { label: "Puertas", section: "puertas" },
      { label: "Chapero", section: "chapero" },
      { label: "Chapero por especialidades", section: "chapero-especialidades" },
      { label: "Contratación de jornada", section: "jornada-contratada" },
      { label: "Puntos Formación", section: "puntos-formacion" }
    ]
  },
  {
    title: "Solicitudes",
    links: [
      { label: "Solicitar dobles y HS", section: "dobles" },
      { label: "Solicitud de vacaciones", section: "vacaciones" },
      { label: "Excluir jornadas", section: "excluir-jornadas" },
      { label: "Jornada Flexible 48h", section: "situacion-trabajador" },
      { label: "Solicito Formación", section: "solicito-formacion" }
    ]
  }
];
