export const PORTAL_HOME_URL = "https://portal.cpevalencia.com/";
// Only these standalone Noray iframe routes were verified without a Portal CPE session.
// Credential-bearing destinations are generated by the server on demand.
export const PORTAL_LINK_GROUPS = [
  {
    title: "Descansos y disponibilidad",
    links: [
      { label: "Disponibilidad · últimos 12 meses", section: "disponibilidad12m" },
      { label: "Solicitar dobles y HS", section: "dobles" }
    ]
  },
  {
    title: "Operativa",
    links: [
      { label: "Puertas", section: "puertas" }
    ]
  },
  {
    title: "Jornada y retribuciones",
    links: [
      { label: "Jornales y primas", section: "jornales" },
      { label: "¿Dónde voy? · Orden de servicio", section: "donde-voy" },
      { label: "Contratación de jornada", section: "jornada-contratada" }
    ]
  },
  {
    title: "Consultas profesionales",
    links: [
      { label: "Mis especialidades", section: "mis-especialidades" },
      { label: "Chapero", section: "chapero" },
      { label: "Chapero por especialidades", section: "chapero-especialidades" }
    ]
  }
];
