with ranked as (
  select id,
    row_number() over (partition by specialty order by updated_at desc, id desc) as rn
  from public.app_cpe_door_snapshots
)
delete from public.app_cpe_door_snapshots d
using ranked r
where d.id = r.id
  and r.rn > 1;

create unique index if not exists app_cpe_door_snapshots_specialty_uidx
  on public.app_cpe_door_snapshots (specialty);

create table if not exists public.app_cpe_usage_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  chapa text,
  metadata jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists app_cpe_usage_events_created_idx
  on public.app_cpe_usage_events (created_at desc);

create index if not exists app_cpe_usage_events_type_created_idx
  on public.app_cpe_usage_events (event_type, created_at desc);

create index if not exists app_cpe_usage_events_chapa_created_idx
  on public.app_cpe_usage_events (chapa, created_at desc);

alter table public.app_cpe_usage_events enable row level security;

revoke all on public.app_cpe_usage_events from anon, authenticated;

drop policy if exists "App CPE usage events are not publicly readable" on public.app_cpe_usage_events;

create or replace function public.app_cpe_track_event(
  p_event_type text,
  p_chapa text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_type text := lower(trim(coalesce(p_event_type, '')));
  v_chapa text := nullif(regexp_replace(coalesce(p_chapa, ''), '\D', '', 'g'), '');
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
begin
  if v_event_type not in ('app_open', 'login', 'register', 'specialties_update') then
    raise exception 'Evento no permitido';
  end if;

  if v_chapa is not null and length(v_chapa) > 5 then
    v_chapa := right(v_chapa, 5);
  end if;

  insert into public.app_cpe_usage_events (event_type, chapa, metadata)
  values (v_event_type, v_chapa, v_metadata);

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.app_cpe_track_event(text, text, jsonb) from public;
grant execute on function public.app_cpe_track_event(text, text, jsonb) to anon, authenticated;

create or replace view public.app_cpe_usage_daily_stats
with (security_invoker = true)
as
select
  date_trunc('day', created_at)::date as day,
  count(*) filter (where event_type = 'app_open') as app_opens,
  count(*) filter (where event_type = 'login') as logins,
  count(*) filter (where event_type = 'register') as registrations,
  count(*) filter (where event_type = 'specialties_update') as specialties_updates,
  count(distinct chapa) filter (where chapa is not null) as unique_chapas
from public.app_cpe_usage_events
group by 1
order by 1 desc;

revoke all on public.app_cpe_usage_daily_stats from anon, authenticated;
